title: Operating System Tips
description: (V001-20200807) URLs.
      <br>May the fork() be with you, Jolan Tru!
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permited here.
author: ABC
show_downloads: false
# google_analytics: 
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github: [metadata]

